name: Run Go tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: "Run Go tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.0
      # The frontend assets are embedded in Go, and the frontend uses Wails assets, requiring the following steps:
      - name: Setup Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.11.0
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Build the Wails frontend assets
        run: wails build
      - name: Build the frontend
        run: cd frontend && npm ci && npm run build && cd ..
      # Actually run the tests:
      - name: Run tests
        run: go test -v ./...